In [8]:
import string

alphabet = string.ascii_lowercase

In [70]:
file_name = '../data/day6.txt'
# file_name = '../data/day2_test2.txt'

with open(file_name, 'r') as f:
    nodes = [np.array(l.rstrip().split(', ')).astype(int) for l in f.readlines()]
    
# data

[array([300,  90]),
 array([300,  60]),
 array([176, 327]),
 array([108, 204]),
 array([297, 303]),
 array([101, 236]),
 array([ 70, 102]),
 array([336, 153]),
 array([260, 265]),
 array([228, 221]),
 array([119, 267]),
 array([310, 302]),
 array([291, 164]),
 array([190, 202]),
 array([298, 228]),
 array([292, 262]),
 array([ 53, 251]),
 array([176,  64]),
 array([170, 160]),
 array([71, 42]),
 array([314,  51]),
 array([71, 88]),
 array([319, 150]),
 array([192, 322]),
 array([270,  88]),
 array([165, 203]),
 array([262, 340]),
 array([301, 327]),
 array([135, 324]),
 array([ 97, 250]),
 array([161, 231]),
 array([305, 344]),
 array([295, 213]),
 array([320, 219]),
 array([172, 269]),
 array([151, 150]),
 array([215, 128]),
 array([167, 102]),
 array([158, 138]),
 array([307, 353]),
 array([358, 335]),
 array([163, 329]),
 array([234, 147]),
 array([ 58, 298]),
 array([228,  50]),
 array([151, 334]),
 array([108, 176]),
 array([335, 235]),
 array([296, 263]),
 array([ 80, 233])]

In [37]:
import numpy as np

def closest_node(node, nodes):
    nodes = np.asarray(nodes)
    dist_2 = np.sum(np.abs(nodes - node), axis=1)
    index = np.argmin(dist_2)
    other_index = len(nodes) - np.argmin(dist_2[::-1]) - 1
    if index == other_index:
        return index

nodes = [
    (1, 1),
    (1, 6),
    (8, 3),
    (3, 4),
    (5, 5),
    (8, 9),
]

node = (0, 5)

closest_node(node, nodes)

1

In [71]:
x_coor, y_coor = list(zip(*nodes))
x_max, y_max = max(x_coor) + 2, max(y_coor) + 2

field = np.empty((y_max, x_max))
for j in range(y_max):
    for i in range(x_max):
        field[j, i] = closest_node((i, j), nodes)
        
field

array([[19., 19., 19., ..., 20., 20., 20.],
       [19., 19., 19., ..., 20., 20., 20.],
       [19., 19., 19., ..., 20., 20., 20.],
       ...,
       [43., 43., 43., ..., 40., 40., 40.],
       [43., 43., 43., ..., 40., 40., 40.],
       [43., 43., 43., ..., 40., 40., 40.]])

In [72]:
_options = set(field.flatten())
_not_options = set(field[0, :]) | set(field[-1, :]) | set(field[:, 0]) | set(field[:, -1])

options = set([el for el in _options if not np.isnan(el)])
not_options = set([el for el in _not_options if not np.isnan(el)])

max_size, max_option = None, None
for option in options - not_options:
    size = sum((field == option).flatten())
    if max_size is None or size > max_size:
        max_option = option
        max_size = size
        
max_size

3260

In [74]:
def total_dist(node, nodes):
    nodes = np.asarray(nodes)
    dist_2 = np.sum(np.abs(nodes - node), axis=1)
    return sum(dist_2)


nodes = [
    (1, 1),
    (1, 6),
    (8, 3),
    (3, 4),
    (5, 5),
    (8, 9),
]

node = (4, 3)

total_dist(node, nodes) == 30

True

In [ ]:
x_coor, y_coor = list(zip(*nodes))
x_max, y_max = max(x_coor) + 2, max(y_coor) + 2

field = np.empty((y_max, x_max))
for j in range(y_max):
    for i in range(x_max):
        field[j, i] = closest_node((i, j), nodes)
        
field